substitutions:
  devicename: humidifier
  upper_devicename: Luftfugter
  restore_mode: ALWAYS_OFF
  led_max_power: "1.0"

packages:
  base: !include packages/base.yaml
  gosund: !include packages/gosund.yaml
